"""add_meal_columns_and_address_pincode

Revision ID: 79f4978eae19
Revises: 
Create Date: 2026-03-25 22:20:52.805797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f4978eae19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('meals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('meals', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('meals', sa.Column('schedule_days', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'schedule_days')
    op.drop_column('meals', 'image_url')
    op.drop_column('meals', 'description')
    op.drop_column('addresses', 'pincode')
    # ### end Alembic commands ###
