"""Add dietary preferences

Revision ID: 7a0b8cd1b145
Revises: d849e7298c52
Create Date: 2026-08-04 08:57:33.698252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0b8cd1b145'
down_revision: Union[str, Sequence[str], None] = 'd849e7298c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('dietary_preference', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('include_eggs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'include_eggs')
    op.drop_column('profiles', 'dietary_preference')
    # ### end Alembic commands ###
