"""add_onboarding_subscriptions_wallet

Revision ID: a23217eda142
Revises: e4495e6d4092
Create Date: 2026-07-12 13:07:54.441704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23217eda142'
down_revision: Union[str, Sequence[str], None] = 'e4495e6d4092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.add_column('meals', sa.Column('available_days', sa.Text(), nullable=True))
    op.drop_column('meals', 'schedule_days')
    op.add_column('order_items', sa.Column('delivery_dates', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('subscription_start_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('subscription_end_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('cod_status', sa.String(length=50), nullable=True))
    op.add_column('vendor_profiles', sa.Column('dietary_type', sa.String(length=50), nullable=True))
    op.add_column('vendor_profiles', sa.Column('service_types', sa.String(length=255), nullable=True))
    op.add_column('vendor_profiles', sa.Column('delivery_windows', sa.Text(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('order_cutoff_hours', sa.Integer(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('max_capacity_per_slot', sa.Integer(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('fssai_number', sa.String(length=100), nullable=True))
    op.add_column('vendor_profiles', sa.Column('is_onboarding_complete', sa.Boolean(), nullable=True))
    op.add_column('vendor_profiles', sa.Column('onboarding_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profiles', 'onboarding_step')
    op.drop_column('vendor_profiles', 'is_onboarding_complete')
    op.drop_column('vendor_profiles', 'fssai_number')
    op.drop_column('vendor_profiles', 'max_capacity_per_slot')
    op.drop_column('vendor_profiles', 'order_cutoff_hours')
    op.drop_column('vendor_profiles', 'delivery_windows')
    op.drop_column('vendor_profiles', 'service_types')
    op.drop_column('vendor_profiles', 'dietary_type')
    op.drop_column('profiles', 'cod_status')
    op.drop_column('orders', 'subscription_end_date')
    op.drop_column('orders', 'subscription_start_date')
    op.drop_column('order_items', 'delivery_dates')
    op.add_column('meals', sa.Column('schedule_days', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('meals', 'available_days')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
