"""Add Feedback to Orders

Revision ID: a3b813a5bb9e
Revises: f5a50039bfc6
Create Date: 2026-07-15 10:59:05.362133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b813a5bb9e'
down_revision: Union[str, Sequence[str], None] = 'f5a50039bfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('feedback_tags', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('feedback_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'feedback_comment')
    op.drop_column('orders', 'feedback_tags')
    op.drop_column('orders', 'rating')
    # ### end Alembic commands ###
