"""add dietary_type to meals

Revision ID: d849e7298c52
Revises: a3b813a5bb9e
Create Date: 2026-07-16 10:52:25.696053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd849e7298c52'
down_revision: Union[str, Sequence[str], None] = 'a3b813a5bb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('dietary_type', sa.String(length=20), server_default='veg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'dietary_type')
    # ### end Alembic commands ###
