"""Add categories

Revision ID: e4495e6d4092
Revises: 79f4978eae19
Create Date: 2026-07-10 16:42:33.348490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4495e6d4092'
down_revision: Union[str, Sequence[str], None] = '79f4978eae19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meals', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'category_id')
    # ### end Alembic commands ###
