"""Add Wallet Transactions

Revision ID: f5a50039bfc6
Revises: 9b656f26564e
Create Date: 2026-07-15 10:44:17.264553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a50039bfc6'
down_revision: Union[str, Sequence[str], None] = '9b656f26564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('is_cod_revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_cod_revoked')
    # ### end Alembic commands ###
